'''
Created on 2012. 9. 14.

@author: jikhanjung
'''

import os
import re
NEWLINE = "\n"

names = [ "Acanthastrea echinata",
"Acanthastrea echinata",
"Acropora palmata",
"Acropora palmata",
"Acropora tenuis",
"Acropora tenuis",
"Acropora cervicornis",
"Agaricia humilis",
"Agaricia humilis",
"Alveopora sp",
"Alveopora sp",
"Anacropora forbesi",
"Anacropora matthai",
"Anacropora matthai",
"Astreopora myriophthalma",
"Astreopora myriophthalma",
"Barabattoia amoricum",
"Barabattoia amoricum",
"Blastomussa merleti",
"Blastomussa wellsi",
"Caulastrea furcata",
"Caulastrea furcata",
"Cladocora arbuscula",
"Cladocora arbuscula",
"Colpophylla natans",
"Coscinaraea columna",
"Coscinaraea columna",
"Coscinaraea columna",
"Cynarina lacrymalis",
"Cynarina lacrymalis",
"Cyphastrea chalcidicum",
"Cyphastrea chalcidium",
"Cyphastrea chalcidium",
"Cyphastrea serialia",
"Cyphastrea suvadivae",
"Dendrogyra cylindrus",
"Dendrogyra cylindrus",
"Dichocoenia stokesi",
"Dichocoenia stokesi",
"Dichocoenia stokesi",
"Dichocoenia stellaris",
"Dichocoenia stokesi",
"Diploastrea heliopora",
"Diploastrea heliopora",
"Diploria clivosa",
"Diploria clivosa",
"Diploria clivosa",
"Diploria Labyrinthiformis",
"Diploria labyrinthiformis",
"Diploria strigosa",
"Diploria strigosa",
"Diploria strigosa",
"Diploria strigosa",
"Echinophyllia aspera",
"Echinophyllia aspera",
"Echinophyllia aspera",
"Echinophyllia aspera",
"Echinophyllia echinoparoides",
"Echinophyllia sp",
"Echinopora gemmacea",
"Echinopora gemmacea",
"Echinopora gemmacea",
"Echinopora gemmacea",
"Echinopora gemmacea",
"Euphyllia ancora",
"Euphyllia ancora",
"Euphyllia ancora",
"Euphyllia glabrescens",
"Euphyllia glabrescens",
"Eusmilia fastigiata",
"Eusmilia fastigiata",
"Favia laxa",
"Favia laxa",
"Favia leptophylla",
"Favia pallida",
"Favia pallida",
"Favia speciosa",
"Favia speciosa",
"Favia speciosa",
"Favia stelligera",
"Favia stelligera",
"Favia stelligera",
"Favia f",
"Favites chinensis",
"Favites chinensis",
"Favites chinensis",
"Favites halicora",
"Favites halicora",
"Favosites halicora",
"Fungia scutaria",
"Fungia scutaria",
"Fungia scutaria",
"Fungia fungites",
"Galaxea fascicularis",
"Galaxea fascicularis",
"Galaxea fascicularis",
"Goniastrea pectinata",
"Goniastrea pectinata",
"Goniastrea pectinata",
"Goniopora sp",
"Goniopora sp",
"Helioseris 1",
"Herpolitha limax",
"Herpolitha limax",
"Herpolitha limax",
"Hydnophora exesa",
"Hydnophora exesa",
"Hydnophora microconos",
"Hydnophora rigida",
"Isophyllia sinuosa",
"Isophyllia sinuosa",
"Leotpastrea fluians",
"Leptastrea pruinosa",
"Leptastrea pruinosa",
"Leptoria phrygia",
"Leptoria phrygia",
"Leptoseris mycetoseroides",
"Lobophyllia corymbosa",
"Lobophyllia corymbosa",
"Lobophyllia corymbosa",
"Lobophyllia hemprichii",
"Lobophyllia hemprichii",
"Lobophyllia hemprichii",
"Lobophyllia pachysepta",
"Lobophyllia pachysepta",
"Madracis mirabilis",
"Madracis mirabilis",
"Manicina areolata",
"Manicina areolata",
"Manicina areolata",
"Meandrina brasiliensis",
"Meandrina brasiliensis",
"Meandrina brasiliensis",
"Meandrina meandrites",
"Meandrina meandrites",
"Meandrina meandrites",
"Merulina ampliata",
"Merulina ampliata",
"Merulina ampliata",
"Merulina scabricula",
"Merulina scabricula",
"Montastraea annularis",
"Montastraea annularis",
"Montastraea cavernosa",
"Montastraea cavernosa",
"Montastraea curta",
"Montastraea curta",
"Montastraea curta",
"Montastraea valenciennesi",
"Montastraea valenciennesi",
"Mussa angulosa",
"Mussa angulosa",
"Mussa angulosa",
"Mussa angulosa",
"Mussismilia braziliensis",
"Mussismilia hartti",
"Mussismilia hartti",
"Mussismilia hispida",
"Mussismilia hispida",
"Mussismilia sp",
"Mussismilia sp",
"Mycedium elephantotus",
"Mycedium elephantotus",
"Mycedium elephantotus",
"Mycetophyllia aliciae",
"Mycetophyllia aliciae",
"Mycetophyllia danaana",
"Mycetophyllia danaana",
"Mycetophyllia lamarckiana",
"Oculina diffusa",
"Oculina diffusa",
"Oculina diffusa",
"Oculina val",
"Oulastrea crispata",
"Oulastrea crispata",
"Oulastrea crispata",
"Oulophyllia crispa",
"Oxypora lacera",
"Oxypora lacera",
"Pachyseris speciosa",
"Pachyseris speciosa",
"Pavona cactus",
"Pavona cactus",
"Pectinia alcicornis",
"Pectinia alcicornis",
"Pectinia lactuca",
"Pectinia paeonia",
"Physogyra lichtensteini",
"Platygyra daedalea",
"Platygyra daedalea",
"Platygyra daedalea",
"Platygyra lamellina",
"Platygyra lamellina",
"Plesiastrea versipora",
"Plesiastrea versipora",
"Pocillopora verrucosa",
"Porites astreoides",
"Porites astreoides",
"Porites lutea",
"Porites lutea",
"Porites astreoides",
"Porites astreoides",
"Porites divaricata",
"Porites porites",
"Porites porites",
"Psammocora contigua",
"Scapophyllia cylindrica",
"Scapophyllia cylindrica",
"Scolymia sp",
"Scolymia sp",
"Scolymia sp",
"Scolymia vitiensis",
"Scolymia vitiensis",
"Scolymia cubensis",
"Seriatopora hystrix",
"Seriatopora hystrix",
"Siderastrea radians",
"Siderastrea radians",
"Siderastrea radians",
"Siderastrea savignyana",
"Siderastrea savignyana",
"Siderastrea siderea",
"Siderastrea siderea",
"Siderastrea sp",
"Siderastrea sp",
"Siderastrea siderea",
"Siderastrea siderea",
"Siderastrea siderea",
"Siderastrea siderea",
"Solenastrea bournoni",
"Solenastrea bournoni",
"Stephanocoenia michelini",
"Stephanocoenia michelini",
"Stephanocoenia michelini",
"Stylocoeniella guentheri",
"Stylocoeniella guentheri",
"Stylocoeniella guentheri",
"Stylophora pistillata",
"Stylophora pistillata",
"Stylophora pistillata",
"Symphyllia agaricia",
"Symphyllia agaricia",
"Symphyllia radians",
"Symphyllia radians",
"Symphyllia recta",
"Symphyllia recta",
"Trachyphyllia geoffroyi",
"Trachyphyllia geoffroyi",
"Turbinaria peltata",
"Turbinaria peltata",
"Turbinaria peltata" ]

count_name = {}
for name in names:
    count_name[name] = 1
print len( count_name )
    

dir = "D:/my documents/"
files = os.listdir( dir )
for fn in files:
    
    ( name, ext ) = os.path.splitext( fn )
    if ext != ".pts": continue
    f = open( dir + fn, 'r' )
    lines = f.read()
    f.close()
    pts_lines = [ l.strip() for l in lines.split( NEWLINE ) ]
    #print pts_lines
    data = pts_lines[2]
    #print "[", data, "]"
    data = data.strip() 
    fpoint = re.split( '\s+', data )
    if fpoint[0] == 'S000':
        print '"' + name + '": "' + " ".join( fpoint[1:4] ) + '",' 